version: "3.8"

services:
  mchs-bot:
    build: .
    container_name: mchs_max_bot
    restart: always
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
    ports:
      - "3030:3030"      # ДЕЛАЕТ АДМИНКУ ДОСТУПНОЙ ИЗ ИНТЕРНЕТА
    volumes:
      - ./src/data:/app/src/data   # сохраняем JSON вне контейнера
